### ISSUE TITLE
Dont show deprecated extensions in the marketplace

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vsmarketplace#23]
![image](https://user-images.githubusercontent.com/32885386/55054798-6043f300-5037-11e9-9cd9-79858c2755ce.png)
These should not be shown anymore

**Comment by ssbarnea** [comment]
The irony is that if you search for “ansible” the first result listed will be microsoft own retired ansible extension, which is still listed first despite having added a “retired” inside description and being unmaintained.

The reality is the marketplace is full of zombies and nothing is done to clean it up. The entire value of the marketplace is diluted because there is no way to hide/archive extensions. 

I will repeat it: too much junk does lower the overall experience for all users, it does not bring any real value.

I even tried using the report option to report unmaintained extensions that used dependencies with critical security issues but apparently the process is very slow and most of the time it has no results at all.

**Comment by ssbarnea** [comment]
@sandy081 Any hints about your last recommendation? My impression was that this was the place to raise bugs for marketplace.

**Comment by sandy081** [comment]
Yes it is.

**Comment by FlorianLaunay** [comment]
Hi @sandy081 , any chance see a change on this? It could be a really usefull feature.

**Comment by isidorn** [comment]
Apart from this the extensions would need to have a deprecated flag. So that VS Code can also render them in a custom way.

**Comment by isidorn** [comment]
@prashantvc I think this request makes overall sense: some way for extensions to say they are deprecated. Assigning to backlog and we should tackle some time in the future.

**Comment by isidorn** [comment]
This feature should allow extension to specify that it is deprecated in favour of another extension - so that VS Code can ask user to install the other extension.

**Comment by isidorn** [comment]
This feature should also allow extensions to specify they are archived - which means no more updates, still working but looking for maintainers.

**Comment by ssbarnea** [comment]
Even if extra metadata is added for deprecation, asking extension developer to re-publish it can prove a real problem. Many may no longer bother to do it as it requires extra work, is not like putting a checkmark on a web form. Many extensions are abandonware, so you cannot even contact original publisher.

This is why earlier this month I released https://marketplace.visualstudio.com/items?itemName=42picky.octarine -- which is an extension that only prompts you to uninstall known problematic extensions. The list is manually picked. Feel free to add a pull-request to it.

**Comment by anangaur** [comment]
My 2 cents: Deprecation and Hiding extensions are 2 different things. Deprecation can mean that a specific extension is deprecated because it's no longer being maintained, or it may have some critical issues. The experience to deprecate extension could have a way to specify (may be by default but can be opted out) that it should be hidden as well. 
Suggested add-ons to deprecation functionality:
- Capability to recommend another extension as an alternative.
- Transfer popularity to the recommended alternative extension. This helps with adoption of the alternative by moving it up the ladder on search results. 

Check out equivalent experiences for NuGet packages:

- https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages
- https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages#transfer-popularity-to-a-newer-package

**Comment by GitMensch** [comment]
So we do have issues marked as duplicate for this which are about showing the deprecation. https://github.com/microsoft/vscode-discussions/discussions/1 also references this issue, because while there is now a way to deprecate an extension and even setup a replecment recommendation, the marketplace still does not show either of those.
@isidorn Shouldn't the deprecation "discussion" should be moved to this repo as it actually _only_ applies to the marketplace (which only handles the deprecation via API but not via webinterface, if I understood it correctly), not to vscode itself?

**Comment by isidorn** [comment]
I think you are right that the discussion belongs here. However since we originally wrongly put it in vscode-discussions I would leave it there (especially since we have some links from our Docs page that point to it).

**Comment by aortiz-msft** [comment]
We hit this today for the NuGet Solver extension which we are no longer supporting. We would like the capability to mark the extension as deprecated and point people to the replacement, the NuGet MCP Server.
